### ISSUE TITLE
Swingbench oewizard and oracle cloud

### ISSUE THREAD

**Issue by robertortel** [domgiles/swingbench-public#12]
Hi

I am trying to setup a swingbench for some test runs with a database in the cloud. I want to run the swingbench client locally on my windows system, and run into some weird issues during the oewizard:

-	OE Wizard 2.6.0.1137
-	Installing Version 2.0
-	Create Order Entry schema
-	Setting up connect details for sys user on my cloud db (without providing a credentials file) <= data is accepted and correct, as I can enter the next steps
-	For the soe user I set up a password complex enough to work the with the requirements for the cloud db (I can create that user manually there and dropped it again afterwards)
-	No partitioning, no compression, Normal Tablespace, All Indexes
-	User defined scale 1
-	Parallelism 1
-	Then I start the creation and the oewizard runs through all steps faster than expected and reports no errors on the graphical interface. However, on the console I can see massive errors:

oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
        at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
        at oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:134)
        at oracle.ucp.common.Database.createPooledConnection(Database.java:256)
        at oracle.ucp.common.Topology.start(Topology.java:247)
        at oracle.ucp.common.Core.start(Core.java:2313)
        at oracle.ucp.common.UniversalConnectionPoolBase.start(UniversalConnectionPoolBase.java:685)
        at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.start(OracleJDBCConnectionPool.java:129)
        at oracle.ucp.admin.UniversalConnectionPoolManagerBase.startConnectionPool(UniversalConnectionPoolManagerBase.java:363)
        at com.dom.datagen.kernel.GenerationManager.createConnectionCache(GenerationManager.java:143)
        at com.dom.datagen.kernel.GenerationManager.<init>(GenerationManager.java:104)
        at com.dom.benchmarking.swingbench.wizards.soedg.OrderEntryGenerate.run(OrderEntryGenerate.java:320)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:456)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:451)
        at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1040)
        at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:552)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:501)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1292)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1025)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:406)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:291)
        at oracle.jdbc.pool.OracleDataSource$1.build(OracleDataSource.java:1683)
        at oracle.jdbc.pool.OracleDataSource$1.build(OracleDataSource.java:1669)
        at oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:103)
        ... 10 more
Jan 07, 2021 3:14:18 PM com.dom.datagen.kernel.GenerationManager run
SEVERE: SQLException in run() of GenerationManager :
java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:456)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:451)
        at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1040)
        at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:552)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:501)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1292)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1025)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:743)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:406)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:291)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:206)
        at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:184)
        at com.dom.datagen.datasource.DatabaseDataSourceFactory.establishConnection(DatabaseDataSourceFactory.java:49)
        at com.dom.datagen.kernel.GenerationManager.run(GenerationManager.java:317)
        at java.lang.Thread.run(Thread.java:748)

Jan 07, 2021 3:14:19 PM com.dom.datagen.kernel.DatabaseGenerationThread run
SEVERE: Unexpected Error when attempting to insert comma delimited row :
java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:456)
        at oracle.ucp.util.UCPErrorHandler.throwSQLException(UCPErrorHandler.java:133)
        at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:928)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1961)
        at oracle.ucp.jdbc.PoolDataSourceImpl.access$400(PoolDataSourceImpl.java:201)
        at oracle.ucp.jdbc.PoolDataSourceImpl$31.build(PoolDataSourceImpl.java:4279)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1917)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1880)
        at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1865)
        at com.dom.datagen.kernel.DatabaseGenerationThread.run(DatabaseGenerationThread.java:53)
        at java.lang.Thread.run(Thread.java:748)
Caused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: ORA-01017: invalid username/password; logon denied

        at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
        at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
        at oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:134)
        at oracle.ucp.common.Database.createPooledConnection(Database.java:256)
        at oracle.ucp.common.Topology.start(Topology.java:247)
        at oracle.ucp.common.Core.start(Core.java:2313)
        at oracle.ucp.common.UniversalConnectionPoolBase.start(UniversalConnectionPoolBase.java:685)
        at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.start(OracleJDBCConnectionPool.java:129)
        at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:924)
        ... 8 more
[...]

In my cloud database actually only the tablespace got created, but no user and no objects.

I am pretty confused by this error, as the sys login seems to have worked during the configuration steps. Do I need such a credential file here? My cloud database is no autonomous database, it is just a database system (on a vm). Or is there something special required for that user to be created?

Thank you for reading. Any ideas are appreciated.

Best regards,
Robert

**Comment by robertortel** [comment]
I changed the users profile on my cloud database to accept any password. With that I switched to a very easy password free of any special characters/symbols. With such an easy password (just lowercase letters) for sys and soe it worked. I did not need such a credential zip file.

The former passwords contained lowercase letters, uppercase letters, numbers and those 3 special characters: - _ #. I can only suspect that '#' might cause issues as it might get interpreted as a comment symbol. All my previous contacts with swingbench (with former versions) used passwords without that character and worked as well.

**Comment by domgiles** [comment]
Ok... So I clearly have an issue that I think I fixed in the build I just created that should stop the build if it can't connect... Re the passwords, I'm running daily on Oracle Cloud. So I'm not sure what the issue would be. First up on OCI are you run mTLS or TLS? what special characters are you using in the password... For instance this password "ThisIsMyPassw0rd!" would need to be entered as "ThisIsMyPassw0rd\!" i.e. escaping the special character. But _ and # should be fine. I can try and create someusers using them and see if I have issues.
