### ISSUE TITLE
OEWizard on ATP runs into ORA-01031 due to ALTER SESSION restrictions

### ISSUE THREAD

**Issue by robertortel** [domgiles/swingbench-public#14]
When OEWizard (on windows) is used to connect to an ATP it fails to insert data into the tables as it runs an

ALTER SESSION SET COMMIT_WAIT=NOWAIT

and such ALTER SESSION option is now allowed on ATP:

https://docs.oracle.com/en/cloud/paas/autonomous-database/adbsa/appendix-restrictions-sql.html#GUID-791E7112-07F7-46F0-BD81-777C8FAD83A0

-----------------------------------------------------------------------
Feb 11, 2021 7:52:36 AM com.dom.datagen.kernel.DatabaseGenerationThread run
SEVERE: Unexpected Error when attempting to insert comma delimited row :
java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
        at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
        at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.execute(Unknown Source)
        at com.dom.datagen.kernel.DataRow.setConnection(DataRow.java:415)
        at com.dom.datagen.kernel.DatabaseGenerationThread.run(DatabaseGenerationThread.java:73)
        at java.lang.Thread.run(Thread.java:748)
Caused by: Error : 1031, Position : 0, Sql = ALTER SESSION SET COMMIT_WAIT=NOWAIT, OriginalSql = ALTER SESSION SET COMMIT_WAIT=NOWAIT, Error Msg = ORA-01031: insufficient privileges

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
        ... 16 more

**Comment by swirkens** [comment]
Problem occurs in asynchronous mode. If You run oewizard with `-async_off` param it will work
