### ISSUE TITLE
Stress_Test.xml Unable to parse config file : java.lang.NullPointerException

### ISSUE THREAD

**Issue by jojolope** [domgiles/swingbench-public#22]
I'm having problems using the Stress_Test config, I've just downloaded 2.6.1163. 

 ./charbench -c ../configs/Stress_Test.xml -debugf
Unable to parse config file : java.lang.NullPointerException please correct the following problem and try again

If I use other config files it seems to read them: 

 ./charbench -c ../configs/SOE_Server_Side_V2.xml -debugf
Swingbench
Author  :        Dominic Giles
Version :        2.6.0.1163

4:50:08 PM FINE     [10] com.dom.benchmarking.swingbench.configuration.Configuration initConfiguration() Connection Refresh set to : null
4:50:08 PM SEVERE   [10] com.dom.benchmarking.swingbench.configuration.Configuration <init>() Error in Processing XML File null
java.lang.NullPointerException
        at com.dom.benchmarking.swingbench.configuration.Configuration.getDriverPrefix(Configuration.java:760)
        at com.dom.benchmarking.swingbench.configuration.Configuration.initConfiguration(Configuration.java:485)
        at com.dom.benchmarking.swingbench.configuration.Configuration.<init>(Configuration.java:339)
        at com.dom.benchmarking.swingbench.CharBench.parseConfig(CharBench.java:185)
        at com.dom.benchmarking.swingbench.CharBench.<init>(CharBench.java:111)
        at com.dom.benchmarking.swingbench.CharBench.main(CharBench.java:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)

I've tried with the previous charbench and same config file and it seems to work: 

./charbench -c ../../swingbench/configs/Stress_Test.xml 
Author  :        Dominic Giles
Version :        2.6.0.1124
...

**Comment by PeterLyndgaard** [comment]
Found a solution:
Its faling in the Driver, current setting in the Stress_Test.xml from 2.6.0.1163 is 
<DriverType>Oracle10g Type IV jdbc driver (thin)</DriverType>
Change it to 
<DriverType>Oracle jdbc Driver</DriverType>
I found this in the other xml's

**Comment by jojolope** [comment]
That works, thanks. 

[root@vm24 configs]$ cd ../bin/
[root@vm24 bin]$ ./charbench -c ../configs/Stress_Test.xml 
Swingbench
Author  :        Dominic Giles
Version :        2.6.0.1163

but only from the bin dir. 

[root@vm24 configs]$ ../bin/charbench -c ./Stress_Test.xml 
SwingBench config file : ./Stress_Test.xml does not exist. Exiting, please try again
[root@vm24 configs]$ ls -l Stress_Test.xml 
-rwx------. 1 lperf wheel 4578 Apr 26 11:29 Stress_Test.xml
