### ISSUE TITLE
results2pdf: An unexpected error occured. Please see the following message null

### ISSUE THREAD

**Issue by TommyCui-2020** [domgiles/swingbench-public#23]
[root@db21c bin]# ls -lrt
total 72
-rwxr-xr-x. 1 root root  118 Nov 17  2010 clusteroverview
-rwxr-xr-x. 1 root root  121 Nov  3  2016 sqlbuilder
-rwxr-xr-x. 1 root root  141 Jul 19  2017 oewizard
-rwxr-xr-x. 1 root root  143 Jul 19  2017 jsonwizard
-rwxr-xr-x. 1 root root  110 Jul 19  2017 minibench
-rwxr-xr-x. 1 root root  110 Jul 19  2017 bmcompare
-rwxr-xr-x. 1 root root  141 Jul 19  2017 ccwizard
-rwxr-xr-x. 1 root root  114 Jul 19  2017 coordinator
-rwxr-xr-x. 1 root root  114 Jul 19  2017 results2pdf
-rwxr-xr-x. 1 root root  107 Jul 19  2017 sbutil
-rwxr-xr-x. 1 root root  141 Jul 19  2017 shwizard
-rwxr-xr-x. 1 root root  112 Jul 19  2017 swingbench
-rwxr-xr-x. 1 root root  150 Jul 19  2017 tpcdswizard
-rwxr-xr-x. 1 root root  352 Jul 20  2017 charbench
-rwxr-xr-x. 1 root root  147 Mar 14 05:11 tpchwizard
drwxr-xr-x. 2 root root 4096 May  6 11:56 data
-rw-r--r--. 1 root root 7904 May  6 12:33 test1.xml
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]# ./results2pdf -c ./test1.xml -o ./test1.pdf
Application :    Results2Pdf
Author      :    Dominic Giles
Version     :    2.6.0.1163
Error : An unexpected error occured. Please see the following message null
[root@db21c bin]#

Why ??

**Comment by tommysway** [comment]
[root@db21c bin]# ./results2pdf -c ./results.xml -o ./ttt.pdf -debug
Application :    Results2Pdf
Author      :    Dominic Giles
Version     :    2.6.0.1163
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults <init>() Starting creation of document
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults <init>() Outputting configuration
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults <init>() Outputting results overview
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults <init>() CPU reading exist too, outputting those
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults <init>() Outputting overview charts
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults createTPSAreaChart() The size of the yData set is 85 and the timingData set is 85
1:17:17 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults createTPSAreaChart() Asking JavaFX to render Chart
1:17:18 PM FINE     [8] com.dom.benchmarking.swingbench.results.ParseResults main() An unexpected error occured java.lang.UnsatisfiedLinkError: Can't load library: /software/swingbench/lib/amd64/libglass.so
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't load library: /software/swingbench/lib/amd64/libglass.so
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:281)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:124)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:182)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:199)
        at com.dom.util.graphsfx.SimpleAreaChart.<init>(SimpleAreaChart.java:45)
        at com.dom.benchmarking.swingbench.results.ParseResults.createTPSAreaChart(ParseResults.java:367)
        at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:209)
        at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:527)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /software/swingbench/lib/amd64/libglass.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:200)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:88)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:31)
        at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:73)
        at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:80)
        at com.sun.glass.ui.gtk.GtkPlatformFactory$1.run(GtkPlatformFactory.java:28)
        at com.sun.glass.ui.gtk.GtkPlatformFactory$1.run(GtkPlatformFactory.java:25)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.<clinit>(GtkPlatformFactory.java:25)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:20)
        at com.sun.glass.ui.Application.Run(Application.java:103)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:271)
        ... 12 more

Error : An unexpected error occured. Please see the following message java.lang.UnsatisfiedLinkError: Can't load library: /software/swingbench/lib/amd64/libglass.so

**Comment by tommysway** [comment]
[root@db21c bin]# java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
[root@db21c bin]#
[root@db21c bin]#
[root@db21c bin]# ./results2pdf -c ./results.xml  -o ./results.pdf
Application :    Results2Pdf
Author      :    Dominic Giles
Version     :    2.6.0.1163
Error : An unexpected error occured. Please see the following message java.lang.UnsatisfiedLinkError: Can't load library: /software/swingbench/lib/amd64/libglass.so
[root@db21c bin]#
[root@db21c bin]#

I changed the JDK, but it still not work.

**Comment by jcnars** [comment]
As noted [here](https://github.com/domgiles/swingbench-public#formatting-the-results-file):
>  Also beware that it only runs on Windows and OSX.

I suspect you are in Linux.
