### ISSUE TITLE
Swingbench2.6 Java error clusterview.bat

### ISSUE THREAD

**Issue by come46** [domgiles/swingbench-public#24]
After coordinator.bat, java lang error. 
Please help me. 

OS: RHEL7.9 
Oracle 19C / RAC
Java Version 1.8.0_333

==== Error Message ====
c:\swingbenchlatest\swingbench\winbin>coordinator.bat -g
Picked up _JAVA_OPTIONS: -Xms512M -Xmx512M
Picked up _JAVA_OPTIONS: -Xms512M -Xmx512M
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: java.lang.NoClassDefFoundError: com/jgoodies/common/base/SystemUtils
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at com.jgoodies.looks.Options.<clinit>(Options.java:441)
        at com.dom.benchmarking.swingbench.coordinator.Coordinator.configureUI(Coordinator.java:123)
        at com.dom.benchmarking.swingbench.coordinator.Coordinator.getOutput(Coordinator.java:73)
        at com.dom.benchmarking.swingbench.coordinator.Coordinator.createCoordinator(Coordinator.java:53)
        at com.dom.benchmarking.swingbench.coordinator.Coordinator.main(Coordinator.java:387)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: com.jgoodies.common.base.SystemUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 19 more

c:\swingbenchlatest\swingbench\winbin>java --version
Picked up _JAVA_OPTIONS: -Xms512M -Xmx512M
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)

**Comment by come46** [comment]
Please Help me:(

**Comment by alexdong2002** [comment]
download jgoodies-common.jar ,put it into swingbench\lib directory ,then restart the coordinator
