### ISSUE TITLE
Intermittent Error in creating the results XML Document : Index: 100, Size: 100

### ISSUE THREAD

**Issue by jojolope** [domgiles/swingbench-public#25]
We have found the following intermittent problem when running charbench: 

charbench -cs //127.0.0.1:1521/pdb -rt 00:30 -u soe -p soe -uc 48 -s -r results/stresstest.xml -c swingbench/configs/Stress_Test.xml

Error in creating the results XML Document : Index: 100, Size: 100
May 16, 2022 9:47:47 PM com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML
SEVERE: Error in creating the results XML Document : 
java.lang.IndexOutOfBoundsException: Index: 100, Size: 100
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at com.dom.benchmarking.swingbench.utilities.NumericHistogram.quantile(NumericHistogram.java:218)
        at com.dom.benchmarking.swingbench.kernel.BenchmarkRecording.getResultsAsXML(BenchmarkRecording.java:162)
        at com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource.getResults(SwingBenchDataSource.java:288)
        at com.dom.benchmarking.swingbench.CharBench.saveResults(CharBench.java:322)
        at com.dom.benchmarking.swingbench.CharBench.lambda$getResults$1(CharBench.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

java.sql.SQLRecoverableException: IO Error: Socket read interrupted
java.sql.SQLRecoverableException: IO Error: Socket read interrupted
java.sql.SQLRecoverableException: IO Error: Socket read interrupted

**Comment by jojolope** [comment]
[debug.log.run.gz](https://github.com/domgiles/swingbench-public/files/8706092/debug.log.run.gz)

**Comment by jojolope** [comment]
[debug.log.create.gz](https://github.com/domgiles/swingbench-public/files/8706113/debug.log.create.gz)
debug log when creating the data
