### ISSUE TITLE
Getting on JDK java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by albertyckwok** [domgiles/swingbench-public#36]
Hi, I am getting the following error on java version "11.0.17" 2022-10-18 LTS. It is out of the box for OCI cloud shell. I am wondering if there is any work around. The following is what I did and get:
```
albert_kwo@cloudshell:~ (us-phoenix-1)$ echo $JAVA_HOME
/usr/java/jdk-11.0.17
albert_kwo@cloudshell:~ (us-phoenix-1)$ java -version
java version "11.0.17" 2022-10-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)
albert_kwo@cloudshell:~ (us-phoenix-1)$ cd swingbench/bin
albert_kwo@cloudshell:bin (us-phoenix-1)$ ./oewizard 
java.lang.UnsupportedClassVersionError: com/dom/benchmarking/swingbench/wizards/Wizard has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.apache.commons.launcher.ChildMain.run(ChildMain.java:183)
albert_kwo@cloudshell:bin (us-phoenix-1)$ 
```
Thanks very much in advance
Albert

**Comment by albertyckwok** [comment]
Never mind, I found my error. The cloud shell comes with JDK 11 instead of 17. I saw the .17 and thinking it is JDK 17. In the cloud shell you can set the JDK to 17 with the following command csruntimectl. The following is what I did to fix the problem:
```
albert_kwo@cloudshell:~ (us-phoenix-1)$ csruntimectl  java list
   graalvmeejdk-17                                               /usr/lib64/graalvm/graalvm22-ee-java17
   oraclejdk-1.8                                                           /usr/java/jdk1.8.0_361-amd64
 * oraclejdk-11                                                                   /usr/java/jdk-11.0.17
albert_kwo@cloudshell:~ (us-phoenix-1)$ csruntimectl  java set graalvmeejdk-17
The current managed java version is set to graalvmeejdk-17.
albert_kwo@cloudshell:~ (us-phoenix-1)$ cd swingbench/bin
albert_kwo@cloudshell:bin (us-phoenix-1)$ ./oewizard -help
```
