### ISSUE TITLE
Error in creating the results XML Document : null

### ISSUE THREAD

**Issue by armoiseev** [domgiles/swingbench-public#37]
results file gets created empty when we try to run json workload
./charbench -c ../configs/JSON_Workload.xml -u swingbench_json -p xxx -uc 100 -cs tcps://xxxx
Swingbench
Author  :        Dominic Giles
Version :        2.7.0.1189

Results will be written to results.xml
Hit Return to Terminate Run...

Time            Users   TPM     TPS

2:42:27 AM      100     91682   1527
Error in creating the results XML Document : null
Mar 23, 2023 2:42:29 AM com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML
SEVERE: Error in creating the results XML Document :
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
        at com.dom.benchmarking.swingbench.kernel.BenchmarkRecording.getResultsAsXML(BenchmarkRecording.java:333)
        at com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource.getResults(SwingBenchDataSource.java:288)
        at com.dom.benchmarking.swingbench.CharBench.saveResults(CharBench.java:322)
        at com.dom.benchmarking.swingbench.CharBench.lambda$getResults$1(CharBench.java:275)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

Saved results to results00006.xml
Completed Run.

**Comment by armoiseev** [comment]
output in debug mode:
`2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Swingbench Version 2.7.0.1189
2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Operating System: Linux
2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Available processors (cores): 64
2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Free memory (bytes): 529559552
2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Maximum memory (bytes): 1073741824
2:58:11 AM FINE     [28] com.dom.benchmarking.swingbench.utilities.LogOSInfo logOSInfo() Total memory available to JVM (bytes): 538968064
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench initCharBench() Not on Windows. No need to install colour support
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench initCharBench() Started CharBench
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.configuration.Configuration initConfiguration() Initialising configuration : "JSON Benchmark"
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.configuration.Configuration initConfiguration() Overview
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.configuration.Configuration initConfiguration() Connection Refresh set to : 0
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.configuration.Configuration initConfiguration() Username = json, Password = enc(J2k1txUC4BU=), Connectstring = jdbc:oracle:thin:@//tpc12server/soe
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.frontend.CommandLineProcessor overrideConfig() Overriding config with command line parameters
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.frontend.CommandLineProcessor overrideConfig() Completed overrideConfig()
2:58:11 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench initCharBench() Verbose outputfile : null
2:58:11 AM FINE     [33] com.dom.benchmarking.swingbench.CharBench run() Starting StdIn listener
Swingbench
Author  :        Dominic Giles
Version :        2.7.0.1189

Results will be written to results.xml
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() Beginning Run
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource <init>() Level of statistics = full
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource init() Initilization of swingbench datasource
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource init() Active Transaction = 4
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() Charbench starting in manual mode
Hit Return to Terminate Run...
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() userSessionManager.start() invoked

Time            Users   TPM     TPS

2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() Entering main loop
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() StateChange
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench isRunning() isRunning returned true
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() State changed to running in run()
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSessionManager init() Initilization UserSessionManager()
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSessionManager initSessions() Initialising all of the sessions, creating 100 new sessions
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() STDebugging = false
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() STConnectionTolerance = 10000
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() MaximumTxRetries = 2
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() STRetriesInterval = 1000
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() STJitter = 0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() maxInterDelay =  0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() maxIntraDelay =  0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() minInterDelay =  0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() minIntraDelay =  0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.UserSession <init>() CommitClientSide = true
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() userSessionManager.init completed
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() listeners added
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource setStartedRun() Start of benchmark : setStartedRun()
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource setStartedRun() Window timings are : bs = 0 be = 0
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording takeSnapShot() Taking Snapshot of Statistics
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() datasource started
2:58:13 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() userSessionManager started logging-on/running users
2:58:13 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.JobManager scheduleJobs() Scheduling jobs
2:58:13 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.UserSessionManager startAllUserSessions() Run time is : 0:00:00
2:58:13 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.UserSessionManager startAllUserSessions() Finished startAllUserSessions()
2:58:14 AM FINE     [51] com.dom.benchmarking.swingbench.benchmarks.JSON.InsertNewPassenger init() Reference data loaded for InsertNewPassenger transaction
2:58:14 AM FINE     [51] com.dom.benchmarking.swingbench.benchmarks.JSON.GetPassengerDetails init() Reference data loaded for GetPassengerDetails transaction
2:58:14 AM FINE     [49] com.dom.benchmarking.swingbench.benchmarks.JSON.UpdatePassengerDetails init() Reference data loaded for UpdatePassengerDetails transaction
2:58:14 AM FINE     [46] com.dom.benchmarking.swingbench.benchmarks.JSON.RemovePassengerDetails init() Reference data loaded for GetPassengerDetails transaction
2:58:15 AM FINE     [62] com.dom.benchmarking.swingbench.kernel.UserSessionManager UserLogOnEvent() All users logged on : State = DOINGNOTHING Real State = RUNNING
2:58:15 AM FINE     [62] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource UserLogOnEvent() All users logged on. Successful = 100 Failed = 0
2:58:42 AM      100     50899   1898
2:58:42 AM FINE     [33] com.dom.benchmarking.swingbench.CharBench run() Got 10
2:58:42 AM FINE     [33] com.dom.benchmarking.swingbench.CharBench setStopped() Signalling
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() StateChange
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench isRunning() isRunning returned false
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() State changed to stop in run()
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench getResults() Call to getResults() : resultsSaved = false
2:58:43 AM FINE     [144] com.dom.benchmarking.swingbench.kernel.UserSessionManager setStopped() Requested to stop running workload
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench getResults() Atempting to write out results to file
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource processStats() Acquired lock
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getDelta() Getting delta of Statistics
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecordingData getDelta() Completed getting the snapshot delta
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getDelta() Finished getting delta Statistics (Clone)
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource processStats() Released lock
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource getResults() Got go ahead to collect stats
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Getting results in XML format via via getResultsAsXML()
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Processing results : Statistics level = full
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.UserSessionManager stopAllUserSession() +-----------------------------------------------------------------------+
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.UserSessionManager stopAllUserSession() | Starting stopAllUserSession(). State of UserSessionManager is STOPPED |
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.kernel.UserSessionManager stopAllUserSession() +-----------------------------------------------------------------------+
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Collecting Transaction info : Data set size = 30
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Collecting system load info : Data set size = 0
Error in creating the results XML Document : null
2:58:43 AM SEVERE   [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Error in creating the results XML Document :  null
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
        at com.dom.benchmarking.swingbench.kernel.BenchmarkRecording.getResultsAsXML(BenchmarkRecording.java:333)
        at com.dom.benchmarking.swingbench.kernel.SwingBenchDataSource.getResults(SwingBenchDataSource.java:288)
        at com.dom.benchmarking.swingbench.CharBench.saveResults(CharBench.java:322)
        at com.dom.benchmarking.swingbench.CharBench.lambda$getResults$1(CharBench.java:275)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.kernel.BenchmarkRecording getResultsAsXML() Finshed getResultsAsXML() in 84ms
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.CharBench saveResults() Results file (results00008.xml) created, getting results
2:58:43 AM FINE     [145] com.dom.benchmarking.swingbench.CharBench saveResults() Results written, closing file
Saved results to results00008.xml
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench getResults() Completed writing out results
2:58:43 AM FINE     [32] com.dom.benchmarking.swingbench.CharBench run() Exiting
Completed Run.
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.CharBench informationEventOccured() Notified that a "Stop Benchmark" Event happened.
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.CharBench getResults() Call to getResults() : resultsSaved = true
2:58:43 AM FINE     [39] com.dom.benchmarking.swingbench.CharBench isRunning() isRunning returned false
`
