### ISSUE TITLE
Cannot find the declaration of element 'SwingBenchConfiguration'

### ISSUE THREAD

**Issue by jerkcsrk** [domgiles/swingbench-public#41]
[root@localhost bin]# ./results2pdf -c /home/soft/dex3-swingbench-result.xml -o /home/soft/dex3-swingbench-result.pdf -debug
Results2Pdf 
Author  :  	 Dominic Giles 
Version :  	 2.7.0.1313 
11:42:39 PM FINE    [12] com.dom.benchmarking.swingbench.results.ParseResults main() An unexpected error occured  null
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 80; cvc-elt.1.a: Cannot find the declaration of element 'SwingBenchConfiguration'.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:548)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:234)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:179)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:164)
	at com.dom.benchmarking.swingbench.jaxb.ResultsFactory.getResults(ResultsFactory.java:33)
	at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:71)
	at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:601)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 80; cvc-elt.1.a: Cannot find the declaration of element 'SwingBenchConfiguration'.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2133)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:571)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:71)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:138)
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1701)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:461)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:407)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:254)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	... 12 more

Error : An unexpected error occured. Please see the following message
 null

**Comment by jerkcsrk** [comment]
I'm Sorry. I'm saved is not a Benchmark profile，save Benchmark profile  can normal use result2pdf.
