### ISSUE TITLE
Error : An unexpected error occured. Please see the following message  null

### ISSUE THREAD

**Issue by BigDataHunter** [domgiles/swingbench-public#45]
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:38:41] sh results2pdf -c results.xml -o results.pdf
Results2Pdf
Author  :  	 Dominic Giles
Version :  	 2.7.0.1423
Error : An unexpected error occured. Please see the following message
 null
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:39:38] sh results2pdf -c taskresults.xml  -o taskresults.pdf -debug
Results2Pdf
Author  :  	 Dominic Giles
Version :  	 2.7.0.1423
下午9:45:46 FINE    [14] com.dom.benchmarking.swingbench.results.ParseResults main() An unexpected error occured  null
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; <Line 1, Column 1>: XML-20108: (Fatal Error) Start of root element expected.]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:548)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:234)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:179)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:164)
	at com.dom.benchmarking.swingbench.jaxb.ResultsFactory.getResults(ResultsFactory.java:33)
	at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:71)
	at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:601)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; <Line 1, Column 1>: XML-20108: (Fatal Error) Start of root element expected.
	at oracle.xml.parser.v2.XMLError.flushErrorHandler(XMLError.java:425)
	at oracle.xml.parser.v2.XMLError.flushErrors1(XMLError.java:291)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:480)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:421)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:249)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	... 12 more

Error : An unexpected error occured. Please see the following message
 null
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:46:03] java -version
java version "17.0.9" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
 why this error please

**Comment by BigDataHunter** [comment]
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:46:08] sh results2pdf -c results.xml  -o taskresults.pdf -debug
Results2Pdf
Author  :  	 Dominic Giles
Version :  	 2.7.0.1423
下午9:46:59 FINE    [14] com.dom.benchmarking.swingbench.results.ParseResults main() An unexpected error occured  null
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 67; columnNumber: 16; cvc-complex-type.2.4.b: 元素 'Result' 的内容不完整。应为 '{"http://www.dominicgiles.com/swingbench":Percentiles, "http://www.dominicgiles.com/swingbench":NinetyFirstPercentile, "http://www.dominicgiles.com/swingbench":NinetySecondPercentile, "http://www.dominicgiles.com/swingbench":NinetyThirdPercentile, "http://www.dominicgiles.com/swingbench":NinetyFourthPercentile, "http://www.dominicgiles.com/swingbench":NinetyFifthPercentile, "http://www.dominicgiles.com/swingbench":NinetySixthPercentile, "http://www.dominicgiles.com/swingbench":NinetySeventhPercentile, "http://www.dominicgiles.com/swingbench":NinetyEigthPercentile, "http://www.dominicgiles.com/swingbench":NinetyNinthPercentile}' 之一。]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:548)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:234)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:179)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:164)
	at com.dom.benchmarking.swingbench.jaxb.ResultsFactory.getResults(ResultsFactory.java:33)
	at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:71)
	at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:601)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: org.xml.sax.SAXParseException; lineNumber: 67; columnNumber: 16; cvc-complex-type.2.4.b: 元素 'Result' 的内容不完整。应为 '{"http://www.dominicgiles.com/swingbench":Percentiles, "http://www.dominicgiles.com/swingbench":NinetyFirstPercentile, "http://www.dominicgiles.com/swingbench":NinetySecondPercentile, "http://www.dominicgiles.com/swingbench":NinetyThirdPercentile, "http://www.dominicgiles.com/swingbench":NinetyFourthPercentile, "http://www.dominicgiles.com/swingbench":NinetyFifthPercentile, "http://www.dominicgiles.com/swingbench":NinetySixthPercentile, "http://www.dominicgiles.com/swingbench":NinetySeventhPercentile, "http://www.dominicgiles.com/swingbench":NinetyEigthPercentile, "http://www.dominicgiles.com/swingbench":NinetyNinthPercentile}' 之一。
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:512)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3600)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3519)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3445)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3347)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2373)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:944)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.endElement(ValidatorHandlerImpl.java:585)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.endElement(ValidatingUnmarshaller.java:76)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:150)
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1689)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:475)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:421)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:249)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	... 12 more

Error : An unexpected error occured. Please see the following message
 null
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:47:00] sh results2pdf -c w
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:47:30] ls
ccwizard            data                minibench           oracle-orcl-500.xml sbutil              swingbench          tpchwizard
charbench           debug.log           moviewizard         results.xml         shwizard            taskresults.xml     wizardlog.xml
coordinator         jsonwizard          oewizard            results2pdf         sqlbuilder          tpcdswizard
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:47:31] sh results2pdf -c wizardlog.xml -o wizardlog.pdf
Results2Pdf
Author  :  	 Dominic Giles
Version :  	 2.7.0.1423
Error : An unexpected error occured. Please see the following message
 null
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:47:46] sh results2pdf -c wizardlog.xml -o wizardlog.pdf -debug
Results2Pdf
Author  :  	 Dominic Giles
Version :  	 2.7.0.1423
下午9:47:51 FINE    [14] com.dom.benchmarking.swingbench.results.ParseResults main() An unexpected error occured  null
javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 62; cvc-elt.1.a: 找不到元素 'LogItems' 的声明。]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:310)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:548)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:234)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:179)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:164)
	at com.dom.benchmarking.swingbench.jaxb.ResultsFactory.getResults(ResultsFactory.java:33)
	at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:71)
	at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:601)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 62; cvc-elt.1.a: 找不到元素 'LogItems' 的声明。
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2133)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:571)
	at com.sun.xml.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:71)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:138)
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1656)
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:475)
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:421)
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:249)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	... 12 more

Error : An unexpected error occured. Please see the following message
 null
matrix@MacBook-Pro:/Volumes/Ventoy/swingbenchlatest/swingbench/bin [21:47:52]

**Comment by BigDataHunter** [comment]
this xml is swingbench genrated,but can not  be prased?

**Comment by eminussleepus** [comment]
I tried with and getting same error,  I tried both Linux and Windows.
