### ISSUE TITLE
Java Error using report2pdf

### ISSUE THREAD

**Issue by aledjones72** [domgiles/swingbench-public#6]
Created a basic benchmark, SOE.  Saved out the output XML,  Tried to use report2pdf and it produces the following error.

# ./results2pdf -c results1.xml
Application :    Results2Pdf
Author      :    Dominic Giles
Version     :    2.6.0.1137
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.launcher.ChildMain.run(ChildMain.java:228)
Caused by: java.lang.NoClassDefFoundError: javafx/scene/paint/Color
        at com.dom.benchmarking.swingbench.results.ParseResults.createTPSAreaChart(ParseResults.java:354)
        at com.dom.benchmarking.swingbench.results.ParseResults.<init>(ParseResults.java:209)
        at com.dom.benchmarking.swingbench.results.ParseResults.main(ParseResults.java:527)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.paint.Color
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 8 more

**Comment by isaacren** [comment]
i've got the same problem, does anyone know how to fix it?

**Comment by PredeeNTNX** [comment]
i've got the same problem, does anyone know how to fix it?

**Comment by domgiles** [comment]
Are you trying to run this on Windows or Mac? Those are the only platforms that the Java libraries are supported at present.
